apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "ci"
spec:
  group: "com.dtwave"
  version: "v1"
  scope: "Namespaced"
  names:
    plural: "cis"
    singular: "ci"
    kind: "Ci"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["replicas"]
          properties:
            replicas:
              type: "integer"
              minimum: 1