---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cis.apps.dtwave.com
spec:
  group: apps.dtwave.com
  names:
    kind: Ci
    listKind: CiList
    plural: cis
    singular: ci
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Ci is the Schema for the cis API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CiSpec defines the desired state of Ci
            properties:
              branch:
                type: string
              model:
                type: string
              repo:
                type: string
              term:
                properties:
                  events:
                    items:
                      type: string
                    type: array
                  schedule:
                    type: string
                required:
                - events
                - schedule
                type: object
              variables:
                additionalProperties:
                  type: string
                type: object
            type: object
          status:
            description: CiStatus defines the observed state of Ci
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
