apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "cis.apps.dtwave.com"
spec:
  group: "apps.dtwave.com"
  scope: "Namespaced"
  names:
    plural: "cis"
    singular: "ci"
    kind: "Ci"
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              model:
                type: string
              repo:
                type: string
              branch:
                type: string
              on:
                type: object
              variables:
                type: object