apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: model-job-sample
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      volumes:
      - name: data
        emptyDir: {}
      - name: dtswap
        emptyDir: {}
      initContainers:
      - image: "alpine/git"
        name: prepare
        env:
        - name: repo
          value: "https://github.com/linjinbao666/vrmanager.git"
        - name: http_proxy
          value: "http://192.168.90.110:1087"
        - name: https_proxy
          value: "http://192.168.90.110:1087"
        args:
        - clone
        - --single-branch
        - --branch=main
        - --
        - "https://github.com/linjinbao666/vrmanager.git"
        - "/opt/workspace"
        volumeMounts:
        - name: data
          mountPath: "/opt/workspace"
      containers:
      - image: "docker.io/linjinbao66/dt-maven:0.0.4"
        name: build
        workingDir: "/opt/workspace"
        env:
        - name: repo
          value: "https://github.com/linjinbao666/vrmanager.git"
        - name: http_proxy
          value: "http://192.168.90.110:1087"
        - name: https_proxy
          value: "http://192.168.90.110:1087"
        - name: PROXY_HOST
          value: "192.168.90.110"
        - name: PROXY_PORT
          value: "1087"
        - name: MAVEN_OPTS
          value: "-DproxySet=true -DproxyHost=192.168.90.110 -DproxyPort=1087"
        command:
        - "/bin/sh"
        - "-c"
        args:
        - "mvn clean package && echo 'success' > /dtswap/mvn.log"
        volumeMounts:
        - name: data
          mountPath: "/opt/workspace"
        - name: dtswap
          mountPath: "/dtswap"
      - name: archive
        image: "docker.io/linjinbao66/dt-mc:0.0.1"
        command:
        - "/bin/sh"
        - "-c"
        args:
        - "while true; do sleep 30 && [ -f '/dtswap/mvn.log' ] && exit 0 || echo 'file not exists'; done"
        volumeMounts:
        - name: data
          mountPath: "/opt/workspace"
        - name: dtswap
          mountPath: "/dtswap"
      restartPolicy: Never
status: {}