apiVersion: apps.dtwave.com/v1
kind: Ci
metadata:
  name: vrmanager-sonar
spec:
  model: "model-sample-sonar"
  repo: "http://192.168.90.154:32578/linjinbao666/vrmanager.git"
  branch: "main"
  term:
    schedule: '28 23 1/7 * *'
    events:
    - push
    - commit
  variables:
    PROJECT_NAME: vrmanager-sonar
    SHUXI_VESION: 0.0.1
