apiVersion: apps.dtwave.com/v1
kind: Model
metadata:
  name: model-sample
spec:
  tasks:
  - name: prepare
    image: busybox:latest
    command: []
    args: 
    - "sh"
    - "-c"
  - name: check
    image: busybox:latest
    command: []
    args: []
  - name: archive
    image: "http://minio.dtwave-inc.com"
    command: []
    args: []
  variables:
    myenv: hello